/*
 * Copyright 2026 Artise.
 *
 * SPDX-License-Identifier: AGPL-3.0-only.
 * Please see LICENSE files in the repository root for full details.
 */

// Artise launcher icon, used instead of :appicon:element.
// The drawables are generated by icon-source/gen.py; edit the script, not the XML.
plugins {
    id("io.element.android-library")
}

android {
    namespace = "co.artise.android.appicon"

    buildTypes {
        register("nightly")
    }
}
