#!/usr/bin/env python3
# Copyright 2026 Artise.
#
# SPDX-License-Identifier: AGPL-3.0-only.
# Please see LICENSE files in the repository root for full details.
"""Write the Firebase string resources from Artise's google-services.json.

The app reads Firebase settings from string resources instead of the Google Services Gradle plugin,
so this copies the values across:
- src/main/res/values/firebase.xml: project-wide values (sender id, API key, project id, bucket);
- src/<buildType>/res/values/firebase.xml: the google_app_id of that build type's package.

These values ship inside every APK and are not secrets. The service-account key Sygnal uses is a secret
and never belongs in this repo.

Usage: artise/tools/firebase_config.py ~/Downloads/google-services.json
"""
import json
import pathlib
import sys
from xml.sax.saxutils import escape

RES_ROOT = pathlib.Path(__file__).resolve().parents[2] / "libraries/pushproviders/firebase/src"
BUILD_TYPE_PACKAGES = {
    "release": "co.artise.app",
    "debug": "co.artise.app.debug",
    "nightly": "co.artise.app.nightly",
}
HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!-- Artise Firebase project. Generated by artise/tools/firebase_config.py from google-services.json. -->
<resources xmlns:tools="http://schemas.android.com/tools">
"""


def string(name, value, unused=False):
    ignore = ' tools:ignore="UnusedResources"' if unused else ""
    return f'    <string name="{name}" translatable="false"{ignore}>{escape(value)}</string>\n'


def main(path):
    data = json.loads(pathlib.Path(path).expanduser().read_text())
    project = data["project_info"]
    clients = {c["client_info"]["android_client_info"]["package_name"]: c for c in data["client"]}
    api_key = next(c["api_key"][0]["current_key"] for c in clients.values() if c.get("api_key"))

    main_xml = HEADER
    main_xml += string("gcm_defaultSenderId", project["project_number"])
    main_xml += string("google_api_key", api_key)
    main_xml += string("google_crash_reporting_api_key", api_key)
    main_xml += string("google_storage_bucket", project["storage_bucket"])
    main_xml += string("project_id", project["project_id"], unused=True)
    main_xml += "</resources>\n"
    (RES_ROOT / "main/res/values/firebase.xml").write_text(main_xml)
    print(f"main: project {project['project_id']}")

    missing = []
    for build_type, package in BUILD_TYPE_PACKAGES.items():
        client = clients.get(package)
        if client is None:
            missing.append(package)
            continue
        xml = HEADER + string("google_app_id", client["client_info"]["mobilesdk_app_id"], unused=True) + "</resources>\n"
        (RES_ROOT / f"{build_type}/res/values/firebase.xml").write_text(xml)
        print(f"{build_type}: {package}")

    if missing:
        print(
            "Not in google-services.json, so those build types can't receive pushes yet: "
            + ", ".join(missing)
            + ". Add them as Android apps in the Firebase project, download the file again and rerun.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    sys.exit(main(sys.argv[1]))
