"""Generate the Artise launcher icon: SVG previews, Android vector drawables and PNGs.

One geometry, three outputs, so the preview is exactly what ships.
Canvas is the adaptive-icon 108x108 dp; the mark stays inside the 66 dp safe circle.
"""
import math
import pathlib
import sys

import cairosvg

OUT = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "out")
OUT.mkdir(parents=True, exist_ok=True)

BLUE = "#22408A"
BLUE_LIGHT = "#2E55B3"
BLUE_DEEP = "#172D63"
YELLOW = "#FFE27A"
YELLOW_DEEP = "#F4CE4B"


# The mark is drawn on a 108 grid, then scaled toward the centre to sit comfortably inside the safe circle.
SCALE = 0.88


def s(x, y):
    return (54 + (x - 54) * SCALE, 54 + (y - 54) * SCALE)


def rounded_polygon(points, radii):
    """Closed path through points with each corner rounded by a quadratic curve."""
    points = [s(*p) for p in points]
    radii = [r * SCALE for r in radii]
    n = len(points)
    parts = []
    for i in range(n):
        prev, cur, nxt = points[i - 1], points[i], points[(i + 1) % n]
        r = radii[i]

        def toward(a, b, d):
            dx, dy = b[0] - a[0], b[1] - a[1]
            length = math.hypot(dx, dy)
            return (a[0] + dx / length * d, a[1] + dy / length * d)

        start = toward(cur, prev, r)
        end = toward(cur, nxt, r)
        parts.append(("M" if i == 0 else "L") + f"{start[0]:.2f},{start[1]:.2f}")
        parts.append(f"Q{cur[0]:.2f},{cur[1]:.2f} {end[0]:.2f},{end[1]:.2f}")
    return " ".join(parts) + " Z"


def sparkle(cx, cy, r, pinch=0.16):
    """Four-point star with concave sides, Ari's mark."""
    cx, cy = s(cx, cy)
    r *= SCALE
    p = r * pinch
    return (
        f"M{cx:.2f},{cy - r:.2f} "
        f"Q{cx + p:.2f},{cy - p:.2f} {cx + r:.2f},{cy:.2f} "
        f"Q{cx + p:.2f},{cy + p:.2f} {cx:.2f},{cy + r:.2f} "
        f"Q{cx - p:.2f},{cy + p:.2f} {cx - r:.2f},{cy:.2f} "
        f"Q{cx - p:.2f},{cy - p:.2f} {cx:.2f},{cy - r:.2f} Z"
    )


# A house whose base turns into a chat bubble's tail: home + conversation.
HOUSE = rounded_polygon(
    [(54, 27), (80, 46.5), (80, 71), (49, 71), (39.5, 81), (39.5, 71), (28, 71), (28, 46.5)],
    [4.5, 4, 5, 2.5, 1.8, 1.2, 5, 4],
)
# Ari: one big sparkle and a small companion.
SPARK_BIG = sparkle(52, 55.5, 11.5)
SPARK_SMALL = sparkle(66.5, 45.5, 4.6)
# A soft lighter band under the roof, drawn only in the colour version.
ROOF_SHADE = rounded_polygon([(54, 27), (80, 46.5), (80, 50), (54, 31), (28, 50), (28, 46.5)], [4.5, 2, 0.5, 0.5, 0.5, 2])

FOREGROUND_SVG = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108">
  <path d="{HOUSE}" fill="{YELLOW}"/>
  <path d="{SPARK_BIG}" fill="{BLUE}"/>
  <path d="{SPARK_SMALL}" fill="{BLUE}"/>
</svg>"""

BACKGROUND_SVG = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108">
  <defs><linearGradient id="g" x1="0" y1="0" x2="108" y2="108" gradientUnits="userSpaceOnUse">
    <stop offset="0" stop-color="{BLUE_LIGHT}"/><stop offset="1" stop-color="{BLUE_DEEP}"/>
  </linearGradient></defs>
  <rect width="108" height="108" fill="url(#g)"/>
</svg>"""

MONO_SVG = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108">
  <path d="{HOUSE} {SPARK_BIG} {SPARK_SMALL}" fill="#000" fill-rule="evenodd"/>
</svg>"""

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!--
  ~ Copyright 2026 Artise.
  ~
  ~ SPDX-License-Identifier: AGPL-3.0-only.
  ~ Please see LICENSE files in the repository root for full details.
  ~
  ~ Generated by artise/appicon/icon-source/gen.py - edit the script, not this file.
  -->
"""

FOREGROUND_XML = HEADER + f"""<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path android:fillColor="{YELLOW}" android:pathData="{HOUSE}" />
    <path android:fillColor="{BLUE}" android:pathData="{SPARK_BIG}" />
    <path android:fillColor="{BLUE}" android:pathData="{SPARK_SMALL}" />
</vector>
"""

BACKGROUND_XML = HEADER + f"""<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path android:pathData="M0,0h108v108h-108z">
        <aapt:attr name="android:fillColor">
            <gradient
                android:type="linear"
                android:startX="0"
                android:startY="0"
                android:endX="108"
                android:endY="108">
                <item android:offset="0" android:color="{BLUE_LIGHT}" />
                <item android:offset="1" android:color="{BLUE_DEEP}" />
            </gradient>
        </aapt:attr>
    </path>
</vector>
"""

MONO_XML = HEADER + f"""<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="#FF000000"
        android:fillType="evenOdd"
        android:pathData="{HOUSE} {SPARK_BIG} {SPARK_SMALL}" />
</vector>
"""


def full_icon_svg(mask):
    """Background plus foreground, clipped to a launcher mask ('square' for Play, 'circle', 'squircle')."""
    clip = {
        "square": '<rect width="108" height="108"/>',
        "circle": '<circle cx="54" cy="54" r="54"/>',
        # The 72 dp visible area launchers show, used for the preview only.
        "visible": '<rect x="18" y="18" width="72" height="72" rx="20"/>',
    }[mask]
    bg = BACKGROUND_SVG.split("\n", 1)[1].rsplit("</svg>", 1)[0]
    fg = FOREGROUND_SVG.split("\n", 1)[1].rsplit("</svg>", 1)[0]
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108">
  <defs><clipPath id="m">{clip}</clipPath></defs>
  <g clip-path="url(#m)">{bg}{fg}</g>
</svg>"""


(OUT / "ic_launcher_foreground.xml").write_text(FOREGROUND_XML)
(OUT / "ic_launcher_background.xml").write_text(BACKGROUND_XML)
(OUT / "ic_launcher_monochrome.xml").write_text(MONO_XML)
(OUT / "foreground.svg").write_text(FOREGROUND_SVG)
(OUT / "monochrome.svg").write_text(MONO_SVG)

# Play Store: 512x512, 32-bit PNG, full square (Play applies its own rounding).
# The adaptive canvas is 108 dp but launchers show the middle 72 dp, so Play's icon zooms to that area.
play = full_icon_svg("square").replace('viewBox="0 0 108 108"', 'viewBox="18 18 72 72"')
cairosvg.svg2png(bytestring=play.encode(), write_to=str(OUT / "ic_launcher-playstore.png"), output_width=512, output_height=512)

for mask in ("circle", "visible"):
    svg = full_icon_svg(mask).replace('viewBox="0 0 108 108"', 'viewBox="18 18 72 72"').replace('r="54"', 'r="36"')
    cairosvg.svg2png(bytestring=svg.encode(), write_to=str(OUT / f"preview_{mask}.png"), output_width=256, output_height=256)
cairosvg.svg2png(bytestring=MONO_SVG.encode(), write_to=str(OUT / "preview_mono.png"), output_width=256, output_height=256)
print("written to", OUT)
